name: WebConsole
main: es.mesacarlos.webconsole.WebConsole
api-version: 1.13
version: 2.1
description: WebSocket-based web console
author: Carlos Mesa
commands:
  WebConsole:
    description: Shows version and active connections of WebConsole
    permission: webconsole.webconsole
    usage: /WebConsole